### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by patrickhoefler** [fbrbovic/kubernetes-reverseproxy#2]
This project looks very interesting! Unfortunately I couldn't find any information about its license. Do you intend to release it under an open source license (e.g. MIT or Apache)?

**Comment by darkgaro** [comment]
Thanks for your interest. 
Actually yes it was always intended as open source, just forgot to add the license, its Apache 2.
I've added it.

**Comment by patrickhoefler** [comment]
Great, thanks! :)
